* Outil de validation des données issues de l'algorithme d'orientation COVID-19

Si votre solution d'orientation COVID-19 est référencée par le
ministère des Solidarités et de la Santé, elle implémente l'algorithme
tel qu'il est [[https://delegation-numerique-en-sante.github.io/covid19-algorithme-orientation/][documenté ici]].

Les fichiers ~csv~ produits par votre solution respectent notamment [[https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation/blob/master/implementation.org#variables-%C3%A0-obligatoirement-sauvegarder-pour-partage][le
schéma de données documenté]].

L'outil de ce dépôt vous permet de tester un ~csv~ pour vérifier que
l'orientation qui y est indiquée correspond à l'orientation telle
qu'elle est calculée par l'algorithme de référence.

* Utilisation

Vous pouvez télécharger le fichier binaire de la [[https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation-check/releases/][dernière version]] puis
le lancer ainsi:

: ~$ covid19-algo-check fichier.csv

Deux fichiers seront produits:

- covid19-algo-check-2020-04-18.csv : contenant la liste des erreurs
  concernant l'orientation.

- covid19-algo-check-2020-04-18.txt : contenant d'autres erreurs.

* Compatibilité

Le fichier binaire est compilé pour les architectures *Linux 64 bits*.

* Licence

2020 DINUM, Bastien Guerry.

Le code source de ce dépôt est publié sous [[file:LICENSE][EPL 2.0 license]].
